
agents:
  queue: "kubernetes"

steps:
  - label: "k8s-image-build"
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: "golang:1.18.3"
                command: [cd hello && go build && buildkite-agent artifact upload hello]

  - block: "Enter Name"
    prompt: "Enter Your Name Kind Good Human"
    branches: "main"
    fields:
      - text: "Your Name"
        key: "hello-name"
    label: "block-and-prompt"


  - commands:
    - chmod +x ./setup_username.sh
    - ./setup_username.sh
    label: "say-howdy"
